# Generated by Django 3.0.4 on 2020-03-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.TextField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('action', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coin_type', models.TextField()),
                ('private_key', models.TextField()),
            ],
        ),
    ]
