# Generated by Django 3.0.2 on 2020-03-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Txn',
            fields=[
                ('txn_id', models.TextField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('status', models.TextField()),
                ('source', models.TextField()),
                ('source_amount', models.TextField()),
                ('source_currency', models.TextField()),
                ('destination', models.TextField()),
                ('destination_amount', models.TextField()),
                ('destination_currency', models.TextField()),
                ('message', models.TextField()),
                ('includes_fee', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
