# Generated by Django 3.0.2 on 2020-03-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='txn',
            name='username',
            field=models.TextField(default='test'),
        ),
    ]
