# Generated by Django 3.0.2 on 2020-03-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
