# Generated by Django 3.0.2 on 2020-03-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20200317_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='coin_type',
            field=models.TextField(default='btc'),
        ),
    ]
